version: '3.8'

services:
  db:
    container_name: db-autodoc
    image: postgres:16.1-alpine
    ports:
      - '5431:5432'
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db

  app:
    container_name: fastapi-app
    build:
      context: .
    env_file:
      - .env
    command: ['/app/scripts/app.sh']
    ports:
      - '8000:8000'
    depends_on:
      - db


volumes:
  postgres-data:
