version: '3'

services:
  db:
    container_name: db_autodoc
    image: postgres:16.1-alpine
    ports:
      - '5437:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: fastapi_app
    build:
      context: .
    env_file:
      - .env
    command: ['/app/scripts/app.sh']
    ports:
      - '8000:8000'
    depends_on:
      - db


volumes:
  postgres_data:
