"""create table excel handle log

Revision ID: cfd9dbabe3d3
Revises: 
Create Date: 2023-12-14 13:48:38.539977

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cfd9dbabe3d3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "excel_handle_logs",
        sa.Column(
            "uuid", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("SUCCESS", "FAILED", name="excelhandlestatus"),
            nullable=True,
        ),
        sa.Column("log", sa.String(), nullable=False),
        sa.Column(
            "error_type",
            sa.Enum(
                "EMPTY",
                "UNSUPPORTED_TYPE",
                "PANDAS_RELATED",
                "INVALID_COLUMNS",
                "INVALID_DATA",
                "OTHER",
                "NONE",
                name="excelhandleerror",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("excel_handle_logs")
    # ### end Alembic commands ###
